# Generated by Django 5.0.4 on 2024-05-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='videos',
        ),
    ]
