# Generated by Django 5.0.4 on 2024-05-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_author_created_alter_author_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
